In [2]:
print(ord('V') % 15 + 1)

# 2, 3, 5, 14, 17, 18, 19, 20, 21

12


In [3]:
import numpy as np
import random
import time

### 1. Виконати набір вправ. Всі завдання виконати 2 способами:
- **а)** з використанням універсальних функцій бібліотеки NumPy [4].
- **b)** за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо).
- **с)** для обох випадків підрахувати час виконання скрипту та зробити висновок.

#### 2, 3, 5, 14, 17, 18, 19, 20, 21

In [4]:
# Task 2

""" 
Вводиться число n. Розставити 1 та 0 у шаховому порядку, починаючи 
з 1 в матриці розміром nхn, використовуючи слайсінг.
"""

def task_2(n: int) -> list[list]:
    arr = [[0] * n for _ in range(n)] # placeholders
    
    for i in range(n):
        for j in range(n):
            arr[i][j] = (i + j) % 2
    
    return arr

def task_2_np(n: int) -> np.ndarray:
    arr = np.zeros((n, n), dtype=int) # placeholders
    
    # Ones in even and odd rows and cols
    arr[::2, ::2] = 1
    arr[1::2, 1::2] = 1
    
    return arr

arr = task_2(5)
arr_np = task_2_np(5)

print("\n".join(" ".join(map(str, row)) for row in arr))
print(arr_np)


0 1 0 1 0
1 0 1 0 1
0 1 0 1 0
1 0 1 0 1
0 1 0 1 0
[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


In [5]:
# Task 3

""" 
Вводяться 4 числа n, m, r, c. Вивести масив розміру n на m, в якому 
в кожному r -му рядку і в кожному c-му стовпчику стоять 0, а інші елементи дорівнюють 1.
"""

def task_3(n, m, r, c) -> list[list]:
    arr = [[1] * m for _ in range(n)]  # placeholders
    
    # 0 in cols by c
    for i in range(n):
        for j in range(0, m, c):
            arr[i][j] = 0
    
    # 0 in rows by r
    for j in range(m):
        for i in range(0, n, r):
            arr[i][j] = 0
    
    return arr

def task_3_np(n, m, r, c) -> np.ndarray:
    arr = np.ones((n, m), dtype=int)  # placeholders
    
    # 0 in cols by c
    arr[::r, :] = 0
    
    # 0 in rows by r
    arr[:, ::c] = 0
    
    return arr

n = 7
m = 7
r = 2
c = 3

start = time.process_time()
arr = task_3(n, m, r, c)
end = time.process_time()
print("Via loops, stms etc: {:.10}".format(end - start))

start = time.process_time()
arr_np = task_3_np(n, m, r, c)
end = time.process_time()
print("Via numpy lib: {:.10f}".format(end - start))

print("\n".join(" ".join(map(str, row)) for row in arr))
print(arr_np)

Via loops, stms etc: 0.00154
Via numpy lib: 0.0006450000
0 0 0 0 0 0 0
0 1 1 0 1 1 0
0 0 0 0 0 0 0
0 1 1 0 1 1 0
0 0 0 0 0 0 0
0 1 1 0 1 1 0
0 0 0 0 0 0 0
[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]]


In [6]:
# Task 5

""" 
Вводиться число n. Вивести масив розміру n на n, в якому в 
рядках з парними індексами стоять 1, а в інших – 0.
"""

def task_5(n: int) -> list[list]:
    arr = [[0] * n for _ in range(n)] # placeholders
    
    for i in range(n):
        if i % 2 == 0:
            arr[i] = [1] * n
    
    return arr

def task_5_np(n: int) -> np.ndarray:
    arr = np.zeros((n, n), dtype=int) # placeholders
    
    # Ones in even and odd rows and cols
    arr[::2] = 1
    
    return arr

arr = task_5(5)
arr_np = task_5_np(5)

print("\n".join(" ".join(map(str, row)) for row in arr))
print(arr_np)

1 1 1 1 1
0 0 0 0 0
1 1 1 1 1
0 0 0 0 0
1 1 1 1 1
[[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]]


In [7]:
# Task 14

""" 
Розмістити на полі 8х8 нулі та одиниці в шахматному 
порядку, використовуючи функцію numpy tile().
"""

def task_14(n) -> np.ndarray:
    a = np.array([[0, 1], [1, 0]])
    arr = np.tile(a, (n // 2, n // 2))
    
    return arr

arr = task_14(8)
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [8]:
# Task 17

""" 
Заповнити вектор значеннями від 0 до n. Замінити 
знаки для всіх значеннь, що менші за n/2 та більші за 3n/4 на протилежні
"""

def task_17(n) -> list[list]:
    vector = [_ for _ in range(n + 1)]  # placeholder

    for i in range(n+1):
        if n//4 < vector[i] < 3*n//4:
            vector[i] = 0

    return vector

def task_17_np(n) -> np.ndarray:
    vector = np.arange(n+1)  # placeholder

    mask = (vector > n//4) & (vector < 3*n//4)
    vector[mask] = 0

    return vector

vec = task_17(10)
vec_np = task_17_np(10)
print(vec)
print(vec_np)


[0, 1, 2, 0, 0, 0, 0, 7, 8, 9, 10]
[ 0  1  2  0  0  0  0  7  8  9 10]


In [9]:
# Task 18

""" 
Згенерувати вектор з n випадкових чисел в діапазоні 
від 0 до 99. Визначити кількість унікальних чисел в послідовності.
"""

task_18 = lambda: len(set([random.randint(0, 99) for _ in range(100)]))

task_18_np = lambda: np.unique(np.random.randint(0, 100, size=100)).size

vec = task_18()
vec_np = task_18_np()
print(vec)
print(vec_np)

65
65


In [10]:
# Task 19

""" 
Згенерувати вектор із n елементів, що рівномірно розміщені на 
інтервалі (0,1) – тобто обидва кінці інтервалу не включені. Значення вивести до 3 знаків після коми.
"""

interval = 1 / (n + 1)
task_19 = lambda n: [round(interval * (i + 1), 3) for i in range(n)] if not n <= 1 else []

task_19_np = lambda n: np.linspace(0.0, 1.0, n+2)[1:-1].round(3) if not n <= 1 else []

vec = task_19(10)
vec_np = task_19_np(10)
print(vec)
print(vec_np)


[0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1.0, 1.125, 1.25]
[0.091 0.182 0.273 0.364 0.455 0.545 0.636 0.727 0.818 0.909]


In [11]:
# Task 20

""" 
Згенерувати вектор із n випадкових елементів, 
що лежать в інтервалі (0,1). Замінити максимальний елемент на 0.
"""

def task_20(n) -> list[list]:
    vector = [random.random() for _ in range(n)]
    print("Source vector: {}".format(vector))
    
    return [0 if i == max(vector) else i for i in vector]

def task_20_np(n) -> np.ndarray:
    vector = np.random.rand(n)
    print("Source vector: {}".format(vector))
    
    vector[np.argmax(vector)] = 0
    return vector


print("Changed vector: {}".format(task_20(5)))
print("Changed vector: {}".format(task_20_np(5)))

Source vector: [0.5321567398949637, 0.20253092969667807, 0.6090564349820314, 0.538231619463144, 0.6165004573688292]
Changed vector: [0.5321567398949637, 0.20253092969667807, 0.6090564349820314, 0.538231619463144, 0]
Source vector: [0.77641442 0.31963278 0.80036412 0.54298997 0.70036021]
Changed vector: [0.77641442 0.31963278 0.         0.54298997 0.70036021]


In [12]:
# Task 21

""" 
Ввести числа n і m. Згенерувати матрицю n на n випадкових цілих 
елементів з діапазону [0, m]. Замінити всі максимальні 
елементи цієї матриці на протилежні за знаком.
"""

def task_21(n, m) -> list[list]:
    arr = [[random.randint(0, m) for _ in range(n)] for _ in range(n)]
    
    for i in range(n):
        for j in range(n):
            if arr[i][j] == max(max(row) for row in arr):
                arr[i][j] *= -1
    
    return arr

def task_21_np(n, m) -> np.ndarray:
    arr = np.random.randint(0, m+1, (n, n))
    
    arr[arr == np.max(arr)] *= -1
    return arr

print("\n".join(" ".join(map(str, row)) for row in task_21(4,10)))
print(task_21_np(4,10))

7 3 2 3
5 0 5 8
3 3 5 0
1 -10 3 3
[[  9   4   5 -10]
 [  8   9   9 -10]
 [  8   8   7   3]
 [  5   6   7 -10]]


### 2. Розв’язати систему за допомогою формул Крамера і виконати перевірку за допомогою:
- **a)** матричного множення;
- **b)** оберненої матриці;
- **c)** функції numpy.linalg.solve().

Порівняти всі рішення за допомогою функції numpy.allclose()

$$
\begin{cases}
\begin{aligned}
x_1 + x_2 - x_3 - x_4 &= 0 \\
x_2 + 2x_3 - x_4 &= 2 \\
x_1 - x_2 - x_4 &= -1 \\
-x_1 + 3x_2 - 2x_3 &= 0
\end{aligned}
\end{cases}
$$

- Матриці $A$ та $B$:

$$
\text{A} = \begin{vmatrix}
1 & 1 & -1 & -1 \\
0 & 1 & 2 & -1 \\
1 & -1 & 0 & -1 \\
-1 & 3 & -2 & 0 \\
\end{vmatrix} \\


\text{B} = \begin{vmatrix}
(0 & 2 & -1 & 0)
\end{vmatrix}
$$

1. Визначимо детермінант(визначник) $A$:

$$
\begin{align*}
&\text{det} = \begin{vmatrix}
1 & 1 & -1 & -1 \\
0 & 1 & 2 & -1 \\ 
1 & -1 & 0 & -1 \\
-1 & 3 & -2 & 0 \\
\end{vmatrix} = \begin{vmatrix}
1 & 1 & -1 & -1 \\
0 & 1 & 2 & -1 \\
0 & -2 & 1 & 0 \\
0 & 4 & -3 & -1 \\
\end{vmatrix} = \begin{vmatrix}
1 & 1 & -1 & -1 \\
0 & 1 & 2 & -1 \\
0 & 0 & 5 & -2 \\
0 & 0 & -11 & 3 \\
\end{vmatrix} = \begin{vmatrix}
1 & 1 & -1 & -1 \\
0 & 1 & 2 & -1 \\
0 & 0 & 5 & -2 \\
0 & 0 & 0 & -1.4 \\
\end{vmatrix} =\\
&\quad = 1 * 1 * 5 * (-1.4) = -7
\end{align*}
$$

2. Визначимо детермінанти(визначники) $A_1, A_2, A_3, A_4$

- Замінимо 1-й стовпець матриці $A$ вектором $B$ -> $A_1$;
- Замінимо 2-й стовпець матриці $A$ вектором $B$ -> $A_2$;
- Замінимо 3-й стовпець матриці $A$ вектором $B$ -> $A_3$;
- Замінимо 4-й стовпець матриці $A$ вектором $B$ -> $A_4$;

$$
\begin{align*}
&\text{det}(A_1) = \begin{vmatrix}
0 & 1 & -1 & -1 \\
2 & 1 & 2 & -1 \\
-1 & -1 & 0 & -1 \\
0 & 3 & -2 & 0 \\
\end{vmatrix} = \begin{vmatrix}
2 & 1 & 2 & -1 \\
0 & 1 & -1 & -1 \\
-1 & -1 & 0 & -1 \\
0 & 3 & -2 & 0 \\
\end{vmatrix} = \begin{vmatrix}
2 & 1 & 2 & -1 \\
0 & 1 & -1 & -1 \\
0 & -0.5 & 1 & -1.5 \\
0 & 3 & -2 & 0 \\
\end{vmatrix} = \begin{vmatrix}
2 & 1 & 2 & -1 \\
0 & 1 & -1 & -1 \\
0 & 0 & 0.5 & -2 \\
0 & 0 & 1 & 3 \\
\end{vmatrix} = \begin{vmatrix}
2 & 1 & 2 & -1 \\
0 & 1 & -1 & -1 \\
0 & 0 & 0.5 & -2 \\
0 & 0 & 0 & 7 \\
\end{vmatrix} =\\
&\quad = 2 \times 1 \times 0.5 \times 7 = -7 \\

&\text{det}(A_2) 
\begin{vmatrix}
1 & 0 & -1 & -1 \\
0 & 2 & 2 & -1 \\ 
0 & -1 & 1 & 0 \\ 
0 & 0 & -3 & -1 \\
\end{vmatrix} = \begin{vmatrix}
1 & 0 & -1 & -1 \\
0 & 2 & 2 & -1 \\
0 & 0 & 2 & -0.5 \\
0 & 0 & -3 & -1 \\
\end{vmatrix} = \begin{vmatrix}
1 & 0 & -1 & -1
0 & 2 & 2 & -1
0 & 0 & 2 & -0.5
0 & 0 & 0 & -1.75
\end{vmatrix} =\\
&\quad = 1 \times 2 \times 2 \times -1.75 = -7 \\

&\text{det}(A_3) = \begin{vmatrix}
1 & 1 & 0 & -1 \\
0 & 1 & 2 & -1 \\
-1 & -1 & -1 & -1 \\
-1 & 3 & 0 & 0 \\
\end{vmatrix} = \begin{vmatrix}
1 & 1 & 0 & -1 \\
0 & 1 & 2 & -1 \\ 
0 & -2 & -1 & 0 \\ 
0 & 4 & 0 & -1 \\
\end{vmatrix} = \begin{vmatrix}
1 & 1 & 0 & -1 \\ 
0 & 1 & 2 & -1 \\ 
0 & 0 & 3 & -2 \\ 
0 & 0 & -8 & 3 \\
\end{vmatrix} = \begin{vmatrix}
1 & 1 & 0 & -1 \\
0 & 1 & 2 & -1 \\ 
0 & 0 & 3 & -2 \\
0 & 0 & 0 & -\frac{7}{3} \\
\end{vmatrix} =\\
&\quad = 1 \times 1 \times 3 \times (-\frac{7}{3}) = -7 \\

&\text{det}(A_4) = \begin{vmatrix}
1 & 1 & -1 & 0 \\
0 & 1 & 2 & 2 \\
1 & -1 & 0 & -1 \\
-1 & 3 & -2 & 0 \\
\end{vmatrix} = \begin{vmatrix}
1 & 1 & -1 & 0 \\
0 & 1 & 2 & 2 \\
0 & -2 & 1&-1 \\
0 & 4 & -3 & 0 \\
\end{vmatrix} = \begin{vmatrix}
1 & 1 & -1 & 0 \\
0 & 1 & 2 & 2 \\
0 & 0 & 5 & 3 \\
0 & 0 & -11	& -8 \\
\end{vmatrix} = \begin{vmatrix}
1 & 1 & -1 & 0 \\
0 & 1 & 2 & 2 \\ 
0 & 0 & 5 & 3 \\ 
0 & 0 & 0 & -1.4 \\
\end{vmatrix} =\\
&\quad = 1 \times 1 \times 5 \times (-1.4) = -7 \\
\end{align*}
$$

3. Знайдемо $x_1, x_2, x_3$ $x_4$ використовуючи правило Крамера:

$$
x_1 = \frac{{\text{det}(A_1)}}{{\text{det}(A)}} = \frac{-7}{-7} = 1
$$

$$
x_2 = \frac{{\text{det}(A_2)}}{{\text{det}(A)}} = \frac{-7}{-7} = 1
$$

$$
x_3 = \frac{{\text{det}(A_3)}}{{\text{det}(A)}} = \frac{-7}{-7} = 1
$$

$$
x_4 = \frac{{\text{det}(A_4)}}{{\text{det}(A)}} = \frac{-7}{-7} = 1
$$

In [13]:
class Testing:
    def __init__(self, A, b):
        self.A = A
        self.b = b

    # Method 1: Matrix Multiplication @
    def test_1(self):
            det_A = np.linalg.det(self.A)
            res = np.empty(len(self.A)) 
            
            for i in range(len(self.A)):
                A_ = self.A.copy()
                A_[:, i] = self.b
                res[i] = np.linalg.det(A_) / det_A
            return res

    # Method 2: Inverse Matrix A-1
    def test_2(self):
            A_inv = np.linalg.inv(self.A)
            return np.dot(A_inv, self.b)

    # Method 3: numpy.linalg.solve()
    def test_3(self):
            return np.linalg.solve(self.A, self.b)

def main():
    A = np.array([[1, 1, -1, -1],
                [0, 1, 2, -1],
                [1, -1, 0, -1],
                [-1, 3, -2, 0]])

    b = np.array([0, 2, -1, 0])

    solver = Testing(A, b)
    
    check_functions = {
    "Checking with matrix multiplication": solver.test_1,
    "Checking with inverse matrix": solver.test_2,
    "Checking with numpy.linalg.solve()": solver.test_3
    }
    
    if all(np.allclose(test(), check_functions["Checking with numpy.linalg.solve()"]()) for test in check_functions.values()):
        print("\n".join("{}: {}".format(k, check_functions[k]()) for k in check_functions))

if __name__ == "__main__":
    main()

Checking with matrix multiplication: [1. 1. 1. 1.]
Checking with inverse matrix: [1. 1. 1. 1.]
Checking with numpy.linalg.solve(): [1. 1. 1. 1.]


### 3. Обчислити значення матричного виразу
- **а)** з використанням універсальних функцій бібліотеки NumPy.
- **b)** за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо).
- **с)** для обох випадків підрахувати час виконання скрипту та зробити висновок.

#### Порівняти всі рішення за допомогою функції numpy.allclose()

In [14]:
class Arr_exp_solver:
    """A(A^2 - B) - 2(B + A)B."""
    
    def __init__(self, A, B) -> None:
        self.A = A
        self.B = B
        
    def expression_via_np(self) -> np.ndarray:
        A_2 = np.dot(self.A, self.A) # A @ A
        res = np.dot(self.A, A_2 - self.B) - 2 * (self.B + self.A) @ self.B
        
        return res
        
    def operation(self, A, operation, B):
        """+, -, *, scalar * of matrices provided"""
        arr = [[0 for _ in range(3)] for _ in range(3)]
        
        if operation == '+': # -> add
            for i in range(3):
                for j in range(3):
                    arr[i][j] = A[i][j] + B[i][j]
        elif operation == '-': # -> subtract
            for i in range(3):
                for j in range(3):
                    arr[i][j] = A[i][j] - B[i][j]
        elif operation == '*': # -> multiply
            for i in range(3):
                for j in range(3):
                    for k in range(3):
                        arr[i][j] += A[i][k] * B[k][j]
        elif operation == 'r*': # -> scalar multiply
            scalar = A
            for i in range(3):
                for j in range(3):
                    arr[i][j] = scalar * B[i][j]
        return arr
    
    def expression(self):
        A_squared = self.operation(self.A, '*', self.A) # A^2
        
        # Full expression ->
        part1 = self.operation(self.A, '*', self.operation(A_squared, '-', self.B))
        part2 = self.operation(2, 'r*', self.operation(self.operation(self.B, '+', self.A), '*', self.B))
        res = self.operation(part1, '-', part2) # <- res of A(A^2 - B) - 2(B + A)B
        
        return res
    
def main():
    A = np.array([[2, 3, 1],
                [-1, 2, 4],
                [5, 3, 0]])

    B = np.array([[2, 7, 13],
                [-1, 0, 5],
                [5, 13, 21]])

    my_solver = Arr_exp_solver(A, B)
    
    start = time.time()
    exp_np = my_solver.expression_via_np()
    end = time.time()
    print("Via numpy lib: {:.6f}".format(end - start))
    
    start = time.time()
    exp = my_solver.expression()
    end = time.time()
    print("Via loops, stms etc: {:.6f}".format(end - start))
    
    if np.allclose(exp, exp_np):
        print("\nVia numpy lib:")
        print(my_solver.expression_via_np())

        print("\nVia loops, stms etc:")
        print("\n".join(" ".join(map(str, row)) for row in my_solver.expression()))

if __name__ == "__main__":
    main()
    

Via numpy lib: 0.000032
Via loops, stms etc: 0.000097

Via numpy lib:
[[  -75  -357  -788]
 [  -40  -156  -359]
 [ -147  -607 -1291]]

Via loops, stms etc:
-75 -357 -788
-40 -156 -359
-147 -607 -1291


In [15]:
class Yep:
    
    def __add__(self, A, B):
        """Addition of two matrices."""
        arr = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
        for i in range(3):
            for j in range(3):
                arr[i][j] = A[i][j] + B[i][j]
        return arr
    
    def __sub__(self, A, B):
        """Subtraction of two matrices."""
        arr = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
        for i in range(3):
            for j in range(3):
                arr[i][j] = A[i][j] - B[i][j]
        return arr
    
    def __mul__(self, A, B):
        """Multiplication of two matrices."""
        arr = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
        for i in range(3):
            for j in range(3):
                for k in range(3):
                    arr[i][j] += A[i][k] * B[k][j]
        return arr
    
    def __rmul__(self, scalar, B):
        """Scalar multiplication of a matrix."""
        arr = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
        for i in range(3):
            for j in range(3):
                arr[i][j] = scalar * B[i][j]
        return arr
    
    def expression(self, A, B):
        # Calculate A^2
        A_2 = self.__mul__(A, A)
        
        res = self.__mul__(A, self.__sub__(A_2, B))
        res = self.__sub__(res, self.__rmul__(2, self.__mul__(self.__add__(B, A), B)))
        
        return res


In [16]:
from IPython.display import display, Javascript

class ExecutionTimeCs:
    def __init__(self):
        self.start_time = None

    def __enter__(self):
        self.start_time = time.process_time()

    def __exit__(self, exc_type, exc_value, traceback):
        end_time = time.process_time()
        elapsed_time = end_time - self.start_time
        print(f"Execution time: {elapsed_time:.6f} seconds")

def exec_time(cell):
    with ExecutionTimeCs():
        display(Javascript(cell))